### ISSUE TITLE
最垃圾的sdk 没有之一

### ISSUE THREAD

**Issue by onizuk** [bihe0832/YSDK#1]
最垃圾的sdk 没有之一

**Comment by bihe0832** [comment]
如果觉得最垃圾，不用说哪里垃圾，就说有哪些最即可，虽然已经不做了，不过我还是可以帮忙反馈建议~

有时候反馈比谩骂效果更好~

**Comment by onizuk** [comment]
垃圾不是谩骂而是是非常贴切的客观描述，反馈你们SDK做的烂的建议想必你们技术客服每天都在收，你的好意心领了

**Comment by bihe0832** [comment]
OK，那这个issues我关闭了~

**Comment by onizuk** [comment]
666 怕别人知道你做的东西很烂吗
